export const ADD_BOOKMARK_CHILD = "ADD_BOOKMARK_CHILD";
export const ADD_FOLDER_CHILD = "ADD_FOLDER_CHILD";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_BOOKMARK = "CREATE_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const DELETE_BOOKMARK_CHILD = "DELETE_BOOKMARK_CHILD";
export const DELETE_FOLDER_CHILD = "DELETE_FOLDER_CHILD";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const RECEIVE_FOLDERS = "RECEIVE_FOLDERS";
export const RECEIVE_BOOKMARKS = "RECEIVE_BOOKMARKS";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const SELECT_BOOKMARK = "SELECT_BOOKMARK";
export const EDIT_FOLDER_NAME = "EDIT_FOLDER_NAME";
export const EDIT_BOOKMARK = "EDIT_BOOKMARK";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
