export const ADD_BOOKMARK_CHILD = "ADD_BOOKMARK_CHILD";
export const ADD_FOLDER_CHILD = "ADD_FOLDER_CHILD";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_BOOKMARK = "CREATE_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const DELETE_BOOKMARK_CHILD = "DELETE_BOOKMARK_CHILD";
export const DELETE_FOLDER_CHILD = "DELETE_FOLDER_CHILD";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const RECEIVE_FOLDERS = "RECEIVE_FOLDERS";
export const RECEIVE_BOOKMARKS = "RECEIVE_BOOKMARKS";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const EDIT_FOLDER_NAME = "EDIT_FOLDER_NAME";

export const TOGGLE_ADD_FOLDER_MODAL = "TOGGLE_ADD_FOLDER_MODAL";
export const TOGGLE_ADD_BOOKMARK_MODAL = "TOGGLE_ADD_BOOKMARK_MODAL";
export const TOGGLE_UPDATE_FOLDER_MODAL = "TOGGLE_UPDATE_FOLDER_MODAL";
export const TOGGLE_UPDATE_BOOKMARK_MODAL = "TOGGLE_UPDATE_BOOKMARK_MODAL";
